- name: (Raspberry Pi - Path) - Creates directory inc path
  file:
    path: "{{ sdr_pi_folder }}/bin/"
    state: directory



- name: (Raspberry Pi - Path) - Update PATH to include {{ sdr_pi_folder }}/bin/
  template:
   src: etc/profile.d/sdr-pi.sh.j2
   dest: /etc/profile.d/sdr-pi.sh
   owner: root
   group: root
   mode: '0755'
