- name: (Raspberry Pi - Packages) - Install aptitude
  apt:
    name: aptitude

- name: (Raspberry Pi - Packages) - Update all packages to the latest version
  apt:
    update_cache: yes
    upgrade: full

- name: (Raspberry Pi - Packages) - Install Some Helpful Packages
  apt:
    pkg:
      - lsof
      - mlocate
      - at
      - bind9-utils
      - bind9-dnsutils
      - tcpdump
      - python3-passlib 

- name: (Raspberry Pi - Packages) - Enable and start at daemon
  become: yes
  service: 
    name: atd
    enabled: yes
    state: started