- name: (Raspberry Pi - Packages) - Install aptitude
  apt:
    name: aptitude

- name: (Raspberry Pi - Packages) - Update all packages to the latest version
  apt:
    update_cache: yes
    upgrade: full
  become: yes
  async: 3600
  poll: 0
  register: package_update

- name: (Raspberry Pi - Packages) - Check on install progress
  async_status:
    jid: "{{ package_update.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 100
  delay: 10

- name: (Raspberry Pi - Packages) - Install Some Helpful Packages
  apt:
    pkg:
      - lsof
      - mlocate
      - at
      - bind9-utils
      - bind9-dnsutils
      - tcpdump
      - python3-passlib 
  become: yes
  async: 3600
  poll: 0
  register: package_helpful

- name: (Raspberry Pi - Packages) - Check on install of helpful packages
  async_status:
    jid: "{{ package_helpful.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 100
  delay: 10

- name: (Raspberry Pi - Packages) - Enable and start at daemon
  become: yes
  service: 
    name: atd
    enabled: yes
    state: started