- name: (Raspberry Pi - Packages) - Install aptitude
  apt:
    name: aptitude

- name: (Raspberry Pi - Packages) - Update all packages to the latest version
  apt:
    update_cache: yes
    upgrade: full
  become: yes
  async: 3600
  poll: 0
  register: package_update

- name: (Raspberry Pi - Packages) - Check on install progress
  async_status:
    jid: "{{ package_update.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 360
  delay: 10

- name: (Raspberry Pi - Packages) - Install Some Helpful Packages
  apt:
    pkg:
      - lsof
      - mlocate
      - at
      - bind9-utils
      - bind9-dnsutils
      - tcpdump
      - python3-passlib 
      - git
  become: yes
  async: 3600
  poll: 0
  register: package_helpful

- name: (Raspberry Pi - Packages) - Check on install of helpful packages
  async_status:
    jid: "{{ package_helpful.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 360
  delay: 10

- name: (Raspberry Pi - Packages) - Remove /var/spool/cron/atjobs to clean up stale at jobs
  file:
    path: "/var/spool/cron/atjobs"
    state: absent

- name: (Raspberry Pi - Packages) - Recreate /var/spool/cron/atjobs to allow at jobs 
  file:
    path: "/var/spool/cron/atjobs"
    state: directory
    owner: daemon
    group: daemon
    mode: '1770'

- name: (Raspberry Pi - Packages) - Recreate /var/spool/cron/atjobs/.SEQ to allow at jobs 
  copy:
    content: ""
    dest: "/var/spool/cron/atjobs/.SEQ"
    force: no
    owner: daemon
    group: daemon

- name: (Raspberry Pi - Packages) - Enable and start at daemon
  become: yes
  service: 
    name: atd
    enabled: yes
    state: started