---
# - name: (Raspberry Pi - Network) - Disable IPv6 on all Interfaces
#   sysctl:
#     name: net.ipv6.conf.all.disable_ipv6 
#     value: '1'
#     sysctl_set: yes
#     state: present
#     reload: yes

# - name: (Raspberry Pi - Network) - Disable IPv6 on default Interfaces
#   sysctl:
#     name: net.ipv6.conf.default.disable_ipv6 
#     value: '1'
#     sysctl_set: yes
#     state: present
#     reload: yes

# - name: (Raspberry Pi - Network) - Disable IPv6 on loopback Interfaces
#   sysctl:
#     name: net.ipv6.conf.lo.disable_ipv6
#     value: '1'
#     sysctl_set: yes
#     state: present
#     reload: yes

- name: (Raspberry Pi - Network) - Configure IPv4 Forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes
