- name: Check Host alive
  ping:

- name: Configure Path
  import_tasks: configure_path.yml

- name: Configure Networking
  import_tasks: configure_network.yml

- name: Configure Firewall
  import_tasks: configure_firewall.yml

- name: Configure to prefer IPv4 to IPv6
  import_tasks: configure_prefer_ipv4.yml

- name: Install Packages
  import_tasks: configure_packages.yml  

- name: Configure SuDo
  import_tasks: configure_sudoers.yml  