- name: (SoapySDR - Packages) - Install Required Packages
  apt:
    pkg:
      - soapyremote-server
      - soapysdr-module-all
      - soapysdr-tools
      - libiio-utils

- name: (SoapySDR - Packages) - Install SDR Support Packages
  apt:
    pkg:
      - airspy
      - bladerf
      - cubicsdr
      - cutesdr
      - gnss-sdr
      - hackrf
      - limesuite
      - limesuite-udev
      - miri-sdr
      - osmo-sdr
      - osmo-trx
      - rtl-sdr
      - qthid-fcd-controller
      - uhd-soapysdr
      - soapysdr-module-uhd

- name: (SoapySDR - Packages) - Install Helpful Packages
  apt:
    pkg:
      - gpsbabel
      - gqrx-sdr
      - inspectrum
      - quisk
      #- hamradio-sdr

- name: (SoapySDR - Packages) - Deploy Environment file for soapyremote-server
  template:
   src: etc/default/soapyremote-server.j2
   dest: /etc/default/soapyremote-server

- name: (SoapySDR - Packages) - Deploy custom SystemD unit for soapyremote-server
  template:
   src: lib/systemd/system/soapyremote-server.service.j2
   dest: /lib/systemd/system/soapyremote-server.service

- name: (SoapySDR - Packages) - Reload and restart soapyremote-server
  systemd:
    daemon_reload: yes
    name: soapyremote-server
    enabled: yes
    state: restarted

