- name: (SoapySDR - Packages) - Install Required Packages
  apt:
    pkg:
      - soapyremote-server
      - soapysdr-module-all
      - soapysdr-tools
      - libiio-utils
  become: yes
  async: 3600
  poll: 0
  register: soapy_install

- name: (SoapySDR - Packages) - Check on install progress
  async_status:
    jid: "{{ soapy_install.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 100
  delay: 10

- name: (SoapySDR - Packages) - Install SDR Support Packages
  apt:
    pkg:
      - airspy
      - airspyhf
      - bladerf
      - cubicsdr
      - cutesdr
      - gnss-sdr
      - hackrf
      - limesuite
      - limesuite-udev
      - miri-sdr
      - osmo-sdr
      - osmo-trx
      - rtl-sdr
      - qthid-fcd-controller
      - uhd-soapysdr
      - uhd-host
      - soapysdr-module-airspy
      - soapysdr-module-audio
      - soapysdr-module-bladerf
      - soapysdr-module-hackrf
      - soapysdr-module-lms7
      - soapysdr-module-mirisdr
      - soapysdr-module-osmosdr
      - soapysdr-module-redpitaya
      - soapysdr-module-remote
      - soapysdr-module-rfspace
      - soapysdr-module-rtlsdr
      - soapysdr-module-uhd
      #- soapysdr-module-xtrx
  become: yes
  async: 3600
  poll: 0
  register: support_install

- name: (SoapySDR - Packages) - Check on support package install progress
  async_status:
    jid: "{{ support_install.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 100
  delay: 10

- name: (SoapySDR - Packages) - Install Helpful Packages
  apt:
    pkg:
      - gpsbabel
      - gqrx-sdr
      - inspectrum
      - quisk
      - hamradio-sdr
      - hamradio-digitalvoice
      - digiham
      - python3-digiham
  become: yes
  async: 3600
  poll: 0
  register: helpful_install

- name: (SoapySDR - Packages) - Check on helpful package install progress
  async_status:
    jid: "{{ helpful_install.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 100
  delay: 10

- name: (SoapySDR - Packages) - Deploy Environment file for soapyremote-server
  template:
   src: etc/default/soapyremote-server.j2
   dest: /etc/default/soapyremote-server

- name: (SoapySDR - Packages) - Deploy custom SystemD unit for soapyremote-server
  template:
   src: lib/systemd/system/soapyremote-server.service.j2
   dest: /lib/systemd/system/soapyremote-server.service

- name: (SoapySDR - Packages) - Reload and restart soapyremote-server
  systemd:
    daemon_reload: yes
    name: soapyremote-server
    enabled: yes
    state: restarted

