- name: (SoapySDR - udev) - Deploy script to bounce soapyremote-server
  template:
   src: usr/sdr-pi/bin/bounce-soapysever-remote.sh.j2
   dest: "{{ sdr_pi_folder }}/bin/bounce-soapysever-remote.sh"
   owner: root
   group: root
   mode: '0755'

- name: (SoapySDR - udev) - Deploy slow bounce soapyremote-server script
  template:
   src: usr/sdr-pi/bin/slow-bounce-soapy.sh.j2
   dest: "{{ sdr_pi_folder }}/bin/slow-bounce-soapy.sh"
   owner: root
   group: root
   mode: '0755'

- name: (SoapySDR - udev) - Deploy udev rules
  template:
   src: etc/udev/rules.d/99-sdr-pi.rules.j2
   dest: /etc/udev/rules.d/99-sdr-pi.rules