---
- name: (SoapySDR - OpenWebRx) - Import GPG Key
  apt_key:
    url: https://repo.openwebrx.de/debian/key.gpg.txt
    state: present

- name: (SoapySDR - OpenWebRx) - Import Apt-Repo
  apt_repository:
    repo: deb https://repo.openwebrx.de/debian/ experimental main
    state: present
    filename: openwebrx

# - name: (SoapySDR - OpenWebRx) - Set the password for the OpenWebRx admin user
#   debconf: name=iptables-persistent question={{ item }} vtype=boolean value=true
#   with_items:
#   - iptables-persistent/autosave_v4

- name: (SoapySDR - OpenWebRx) - Install OpenWebRx Packages
  apt:
    pkg:
      - openwebrx
      - soapy-connector
    update_cache: yes
