---
- name: (SoapySDR - BladeRF) - Check to see if BladeRF firmware is present 
  stat: path=/usr/share/Nuand/bladeRF/bladeRF_fw.img
  register: bladerf_fw

- name: (SoapySDR - BladeRF) - Download Firmware
  command: "/usr/bin/bladeRF-install-firmware"
  args: 
    creates: /usr/share/Nuand/bladeRF/bladeRF_fw.img
  when: not bladerf_fw.stat.exists