---
- name: (SoapySDR - Ettus UHD) - Check to see if BladeRF firmware is present 
  stat: path=/usr/share/uhd/images/inventory.json
  register: bladerf_fw

- name: (SoapySDR - Ettus UHD) - Download Firmware
  command: "/usr/bin/uhd_images_downloader"
  args: 
    creates: /usr/share/uhd/images/inventory.json
  when: not bladerf_fw.stat.exists