---
- name: (SoapySDR - Radioberry) - Install Radioberry Required Packages
  apt:
    pkg:
      - cmake
      - libad9361-dev
      - libiio-dev
    update_cache: yes
  become: yes
  async: 3600
  poll: 0
  register: radioberry_req_packages_install

- name: (SoapySDR - Radioberry) - Check on install progress for required tools
  async_status:
    jid: "{{ radioberry_req_packages_install.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 360
  delay: 10

- name: (SoapySDR - Radioberry) - Check to see if Radioberry has already been deployed    
  stat: 
    path: "/usr/local/lib/SoapySDR/modules0.7/libSoapyRadioberrySDR.so"
  register: radioberry

- name: (SoapySDR - Radioberry) - Ensure we have src folder for compilation
  file:
    path: "{{ sdr_pi_folder }}/src"
    state: directory

- name: (SoapySDR - Radioberry) - Download Radioberry and extract it to {{ sdr_pi_folder }}/src/Radioberry-2.x
  git:
    repo: https://github.com/pa3gsb/Radioberry-2.x.git
    dest: "{{ sdr_pi_folder }}/src/Radioberry-2.x"

- name: (SoapySDR - Radioberry) - Ensure we have build folder for compilation
  file:
    path: "{{ sdr_pi_folder }}/src/Radioberry-2.x/SBC/rpi-4/SoapyRadioberrySDR/build"
    state: directory


- name: (SoapySDR - Radioberry) - Cmake Radioberry
  command: "/usr/bin/cmake .."
  args: 
    chdir: "{{ sdr_pi_folder }}/src/Radioberry-2.x/SBC/rpi-4/SoapyRadioberrySDR/build"
    creates: "{{ sdr_pi_folder }}/src/Radioberry-2.x/SBC/rpi-4/SoapyRadioberrySDR/build/Makefile"
  become: yes
  async: 3600
  poll: 0
  register: cmake_radioberry
  when: not radioberry.stat.exists        

- name: (SoapySDR - Radioberry) - Check on cmake progress
  async_status:
    jid: "{{ cmake_radioberry.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 360
  delay: 10
  when: not radioberry.stat.exists  

- name: (SoapySDR - Radioberry) - Make Radioberry
  command: "/usr/bin/make -j4"
  args: 
    chdir: "{{ sdr_pi_folder }}/src/Radioberry-2.x/SBC/rpi-4/SoapyRadioberrySDR/build"
    creates: "{{ sdr_pi_folder }}/src/Radioberry-2.x/SBC/rpi-4/SoapyRadioberrySDR/build/libSoapyRadioberrySDR.so"
  become: yes
  async: 3600
  poll: 0
  register: make_radioberry
  when: not radioberry.stat.exists        

- name: (SoapySDR - Radioberry) - Check on make progress
  async_status:
    jid: "{{ make_radioberry.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 360
  delay: 10
  when: not radioberry.stat.exists  

- name: (SoapySDR - Radioberry) - Install Radioberry
  command: "/usr/bin/make install"
  args: 
    chdir: "{{ sdr_pi_folder }}/src/Radioberry-2.x/SBC/rpi-4/SoapyRadioberrySDR/build"
    creates: "/usr/local/lib/SoapySDR/modules0.7/libSoapyRadioberrySDR.so"
  become: yes
  async: 3600
  poll: 0
  register: make_install_radioberry
  when: not radioberry.stat.exists        

- name: (SoapySDR - Radioberry) - Check on Installation Progress
  async_status:
    jid: "{{ make_install_radioberry.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 360
  delay: 10
  when: not radioberry.stat.exists  

