---
- name: (SoapySDR - FCDPP) - Install PlutoSDR Required Packages
  apt:
    pkg:
      - libsoapysdr-dev
      - soapysdr-tools
      - libhidapi-dev 
      - libasound2-dev
    update_cache: yes
  become: yes
  async: 3600
  poll: 0
  register: funcube_req_packages_install

- name: (SoapySDR - FCDPP) - Check on install progress for required tools
  async_status:
    jid: "{{ funcube_req_packages_install.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 100
  delay: 10

- name: (SoapySDR - FCDPP) - Check to see if FCDPP has already been deployed    
  stat: 
    path: "/usr/local/lib/SoapySDR/modules0.7/libFCDPPSupport.so"
  register: funcube

- name: (SoapySDR - FCDPP) - Ensure we have src folder for compilation
  file:
    path: "{{ sdr_pi_folder }}/src"
    state: directory

- name: (SoapySDR - FCDPP) - Download FCDPP and extract it to {{ sdr_pi_folder }}/src/SoapyFCDPP
  git:
    repo: https://github.com/pothosware/SoapyFCDPP.git
    dest: "{{ sdr_pi_folder }}/src/SoapyFCDPP"

- name: (SoapySDR - FCDPP) - Ensure we have build folder for compilation
  file:
    path: "{{ sdr_pi_folder }}/src/SoapyFCDPP/build"
    state: directory


- name: (SoapySDR - FCDPP) - Cmake FCDPP
  command: "/usr/bin/cmake .."
  args: 
    chdir: "{{ sdr_pi_folder }}/src/SoapyFCDPP/build"
    creates: "{{ sdr_pi_folder }}/src/SoapyFCDPP/build/Makefile"
  become: yes
  async: 3600
  poll: 0
  register: cmake_funcube
  when: not funcube.stat.exists        

- name: (SoapySDR - FCDPP) - Check on cmake progress
  async_status:
    jid: "{{ cmake_funcube.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 360
  delay: 10
  when: not funcube.stat.exists  

- name: (SoapySDR - FCDPP) - Make FCDPP
  command: "/usr/bin/make"
  args: 
    chdir: "{{ sdr_pi_folder }}/src/SoapyFCDPP/build"
    creates: "{{ sdr_pi_folder }}/src/SoapyFCDPP/build/libFCDPPSupport.so"
  become: yes
  async: 3600
  poll: 0
  register: make_funcube
  when: not funcube.stat.exists        

- name: (SoapySDR - FCDPP) - Check on make progress
  async_status:
    jid: "{{ make_funcube.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 360
  delay: 10
  when: not funcube.stat.exists  

- name: (SoapySDR - FCDPP) - Install FCDPP
  command: "/usr/bin/make install"
  args: 
    chdir: "{{ sdr_pi_folder }}/src/SoapyFCDPP/build"
    creates: "/usr/local/lib/SoapySDR/modules0.7/libFCDPPSupport.so"
  become: yes
  async: 3600
  poll: 0
  register: make_install_funcube
  when: not funcube.stat.exists        

- name: (SoapySDR - FCDPP) - Check on Installation Progress
  async_status:
    jid: "{{ make_install_funcube.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 100
  delay: 10
  when: not funcube.stat.exists  

