---
- name: (SoapySDR - FifiSDR) - Install FifiSDR Required Packages
  apt:
    pkg:
      - soapysdr-tools
      - libairspyhf-dev
      - libpopt-dev
    update_cache: yes
  become: yes
  async: 3600
  poll: 0
  register: fifisdr_req_packages_install

- name: (SoapySDR - FifiSDR) - Check on install progress for required tools
  async_status:
    jid: "{{ fifisdr_req_packages_install.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 100
  delay: 10

- name: (SoapySDR - FifiSDR) - Check to see if FifiSDR has already been deployed    
  stat: 
    path: "/usr/local/lib/SoapySDR/modules0.7/libairspyhfSupport.so3"
  register: fifisdr

- name: (SoapySDR - FifiSDR) - Ensure we have src folder for compilation
  file:
    path: "{{ sdr_pi_folder }}/src"
    state: directory

- name: (SoapySDR - FifiSDR) - Download FifiSDR and extract it to {{ sdr_pi_folder }}/src/rockprog-linux
  git:
    repo: https://github.com/sclow/rockprog-linux.git
    dest: "{{ sdr_pi_folder }}/src/rockprog-linux"

- name: (SoapySDR - FifiSDR) - Make FifiSDR
  command: "/usr/bin/make"
  args: 
    chdir: "{{ sdr_pi_folder }}/src/rockprog-linux"
    creates: "{{ sdr_pi_folder }}/src/rockprog-linux/rockprog"
  become: yes
  async: 3600
  poll: 0
  register: make_fifisdr
  when: not fifisdr.stat.exists        

- name: (SoapySDR - FifiSDR) - Check on make progress
  async_status:
    jid: "{{ make_fifisdr.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 360
  delay: 10
  when: not fifisdr.stat.exists  

- name: (SoapySDR - FifiSDR) - Install FifiSDR
  copy: 
    remote_src: True 
    src: "{{ sdr_pi_folder }}/src/rockprog-linux/rockprog"
    dest: /usr/bin/rockprog
    owner: root
    group: root
    mode: "0755"
