- name: (SoapySDR) Check Host alive
  ping:

- name: (SoapySDR) Install Packages
  import_tasks: configure_packages.yml  

- name: (SoapySDR) Deploy OpenWebRx WebSDR
  import_tasks: deploy_openwebrx_websdr.yml

- name: (SoapySDR) Install DREAM Plugin
  import_tasks: install_dream.yml

- name: (SoapySDR) Deploy udev rules
  import_tasks: deploy_udev_rules.yml

- name: (SoapySDR) Get BladeRF Firmware
  import_tasks: get_bladerf_firmware.yml

- name: (SoapySDR) Get Ettus/UHD Firmware
  import_tasks: get_uhd_firmware.yml