- name: (SoapySDR) Check Host alive
  ping:

- name: (SoapySDR) Install Packages
  import_tasks: configure_packages.yml  

- name: (SoapySDR) Deploy OpenWebRx WebSDR
  import_tasks: deploy_openwebrx_websdr.yml

- name: (SoapySDR) Deploy udev rules
  import_tasks: deploy_udev_rules.yml