---
# Required to parse all variables
- hosts: all

- hosts: sdr_pis
  roles:
    - raspberry_pi
    - wireless_ap
    - certificate_authority
    - webserver
    - soapysdr_server
    #- readonly_pi
