---
- name: (Wireless - DNSMasq) - Create dnsmasq Config Directory (/etc/dnsmasq.sdr)
  file:
    path: /etc/dnsmasq.sdr
    state: directory

- name: (Wireless - DNSMasq) - Create dnsmasq configuration for wlan0
  template:
   src: etc/dnsmasq.sdr/wlan0.j2
   dest: /etc/dnsmasq.sdr/wlan0

- name: (Wireless - DNSMasq) - Create dnsmasq configuration for eth0
  template:
   src: etc/dnsmasq.sdr/eth0.j2
   dest: /etc/dnsmasq.sdr/eth0

- name: (Wireless - DNSMasq) - Create dnsmasq configuration for wildcard
  template:
   src: etc/dnsmasq.sdr/wildcard.j2
   dest: /etc/dnsmasq.sdr/wildcard

- name: (Wireless - DNSMasq) - Activate dnsmasq configuration for wlan0
  file:
    src: /etc/dnsmasq.sdr/wlan0
    dest: /etc/dnsmasq.d/wlan0
    owner: root
    group: root
    state: link
    force: true

- name: (Wireless - DNSMasq) - Activate dnsmasq configuration for wildcard
  file:
    src: /etc/dnsmasq.sdr/wildcard
    dest: /etc/dnsmasq.d/wildcard
    owner: root
    group: root
    state: link
    force: true


- name: (Wireless - DNSMasq) - Make sure the dnsmasq service is unmasked, restarted, and enabled
  systemd:
    name: dnsmasq
    state: restarted
    enabled: yes
    masked: no
