---
- name: (Wireless - HostAPD) - Deploy Configuration
  template:
   src: etc/hostapd/hostapd.tmpl.j2
   dest: /etc/hostapd/hostapd.tmpl

- name: (Wireless - HostAPD) - Deploy SystemD Unit
  template:
   src: lib/systemd/system/hostapd.service.j2
   dest: /lib/systemd/system/hostapd.service

- name: (Wireless - HostAPD) - Creates directory inc path
  file:
    path: "{{ sdr_pi_folder }}/bin/"
    state: directory

- name: (Wireless - HostAPD) - Deploy SSID Changing Script
  template:
   src: usr/sdr-pi/bin/dynamic-ssid-from-mac.sh.j2
   dest: "{{ sdr_pi_folder }}/bin/dynamic-ssid-from-mac.sh"
   owner: root
   group: root
   mode: '0755'


- name: (Wireless - HostAPD) - Make sure the service is unmasked, started, and enabled
  systemd:
    name: hostapd
    state: started
    enabled: yes
    masked: no

