- name: (Bettercap - Packages) - Install Required Packages
  apt:
    pkg:
      - golang
      - git
      - build-essential
      - libpcap-dev
      - libusb-1.0-0-dev
      - libnetfilter-queue-dev
