---
- name: (Certificate Authority - Initialise) - Check to see if EasyRSA3 PKI has already been initialised    
  stat: path="{{ sdr_pi_folder }}/pki"
  register: pki

- name: (Certificate Authority - Initialise) - Initialise PKI Infrastructure
  command: "{{ sdr_pi_folder }}/easyrsa3/easyrsa init-pki "
  args: 
    creates: "{{ sdr_pi_folder }}/easyrsa3/pki"
  when: not pki.stat.exists

- name: (Certificate Authority - Initialise) - Create Certificate Authority
  command: "{{ sdr_pi_folder }}/easyrsa3/easyrsa --batch --req-cn='{{ certificate_authority_name }}-{{ eth0_mac_address}}' build-ca nopass"
  args: 
    creates: "{{ sdr_pi_folder }}/pki/ca.crt"

- name: (Certificate Authority - Initialise) - Create Dummy Req for revokeME
  command: "{{ sdr_pi_folder }}/easyrsa3/easyrsa --batch gen-req revokeME nopass"
  args: 
    creates: "{{ sdr_pi_folder }}/pki/reqs/revokeME.req"

- name: (Certificate Authority - Initialise) - Create Dummy Cert for revokeME
  command: "{{ sdr_pi_folder }}/easyrsa3/easyrsa --batch sign-req client revokeME" 
  args: 
    creates: "{{ sdr_pi_folder }}/pki/issued/revokeME.crt"

- name: (Certificate Authority - Initialise) - Revoke revokeME in order to be able to create CRL
  command: "{{ sdr_pi_folder }}/easyrsa3/easyrsa --batch revoke revokeME cessationOfOperation" 
  args: 
    removes: "{{ sdr_pi_folder }}/pki/private/revokeME.key"

- name: (Certificate Authority - Initialise) - Create CRL
  command: "{{ sdr_pi_folder }}/easyrsa3/easyrsa --batch gen-crl" 
  args: 
    creates: "{{ sdr_pi_folder }}/pki/crl.pem"