---
- name: (Webserver - Apache) - Install Apache2 Packages
  apt:
    pkg:
      - apache2
      - apache2-doc
      - apache2-utils
      - php-pear
      - libapache2-mod-php7.4
    update_cache: yes
  become: yes
  async: 3600
  poll: 0
  register: apache_install

- name: (Webserver - Apache) - Check on install progress
  async_status:
    jid: "{{ apache_install.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 360
  delay: 10

- name: (Webserver - Apache) - Enable Apache WebDAV modules
  apache2_module:
    state: present
    name: "{{item}}"
  with_items:
    - auth_digest
    - dav
    - dav_fs

- name: (Webserver - Apache) - Remove WebDAV folder prior to deployment
  file:
    path: "{{ sdr_pi_folder }}/wiki/data"
    state: absent

- name: (Webserver - Apache) - Required folders
  file:
    path: "{{ sdr_pi_folder }}/{{item}}/"
    state: directory
    owner: www-data
    group: www-data
  with_items:
    - DavLock
    - webdav
    - wiki

- name: (Webserver - Apache) - Create and propagate htdigest file for authentication
  template:
    src: etc/apache2/htdigest.j2
    dest: "{{ sdr_pi_folder }}/DavLock//users.password"
    owner: root
    group: www-data
    mode: "0640"

- name: (Webserver - Apache) - Deploy Apache Security config
  template:
    src: etc/apache2/conf-available/security.conf.j2
    dest: /etc/apache2/conf-available/security.conf

- name: (Webserver - Apache) - Deploy Apache Port config
  template:
    src: etc/apache2/ports.conf.j2
    dest: /etc/apache2/ports.conf

- name: (Webserver - Apache) - Deploy Apache Site config
  template:
    src: etc/apache2/sites-available/000-default.conf.j2
    dest: /etc/apache2/sites-available/000-default.conf

- name: (Webserver - Apache) - Deploy Apache Landing Page (derived from template)
  template:
    src: var/www/html/index.html.j2
    dest: /var/www/html/index.html

- name: (Webserver - Apache) - Restart Apache web server
  become: yes
  service: 
    name: apache2
    enabled: yes 
    state: restarted

- name: (Webserver - Apache) - Deploy WebDav content
  git:
    repo: "{{ sdr_pi_admin_webdav_git_repo }}"
    dest: "{{ sdr_pi_folder }}/webdav"
    force: yes
    accept_newhostkey: yes
  when: (sdr_pi_admin_webdav_git_repo is defined) and (sdr_pi_admin_webdav_git_repo | length > 0)

- name: (Webserver - Apache) - Set Permissions on WebDav content
  file: 
    dest: "{{ sdr_pi_folder }}/webdav"
    owner: www-data 
    group: www-data 
    mode: "u=rwX,g=rX,o=rX"
    recurse: yes