---
- name: (Webserver - NginX) - Install NginX Packages
  apt:
    pkg:
      - nginx

- name: (Webserver - NginX) - Deploy NginX config /etc/nginx/nginx.conf
  template:
   src: etc/nginx/nginx.conf.j2
   dest: /etc/nginx/nginx.conf

- name: (Webserver - NginX) - Deploy NginX snippet /etc/nginx/snippets/sdr-pi-ssl
  template:
   src: etc/nginx/snippets/sdr-pi-ssl.conf.j2
   dest: /etc/nginx/snippets/sdr-pi-ssl.conf

- name: (Webserver - NginX) - Deploy NginX default site /etc/nginx/sites-available/default
  template:
   src: etc/nginx/sites-available/default.j2
   dest: /etc/nginx/sites-available/default

- name: (Webserver - NginX) - Expose CA Certificate for download
  ansible.builtin.file:
    src: "{{ certificate_authority_cert_file }}"
    dest: /usr/share/nginx/html/cert.pem
    owner: root
    group: root
    state: link
    force: true

- name: (Webserver - NginX) - Restart NginX to pick up custom config
  become: yes
  service: 
    name: nginx
    enabled: yes 
    state: restarted