---
- name: (Webserver) Check Host alive
  ping:

- name: (Webserver) Deploy Apache
  import_tasks: deploy_apache.yml

- name: (Webserver) Deploy Dokuwiki
  import_tasks: deploy_dokuwiki.yml

# - name: (Webserver) Deploy HAProxy
#   import_tasks: deploy_haproxy.yml

- name: (Webserver) Deploy NginX
  import_tasks: deploy_nginx.yml